services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY:-masterKey} # Default master key for development
      - MEILI_NO_ANALYTICS=true # Disable analytics
      - MEILI_ENV=${NODE_ENV:-development}
    ports:
      - '7700:7700'
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--spider',
          'http://localhost:7700/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  meilisearch_data:
